/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:1f18cd64-3abb-4708-956a-40ae308a215e",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_sKszz61bM",
    "aws_user_pools_web_client_id": "5vofu1cv4tmdgqs9egs5ieila9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ysv2uwhnxvf4tdtzhtpwbaka6u.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "popularcimages184647-qa",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "predictions": {
        "identify": {
            "identifyLabels": {
                "proxy": false,
                "region": "eu-west-2",
                "defaults": {
                    "type": "LABELS"
                }
            }
        }
    }
};


export default awsmobile;
